global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gradio_app'
    static_configs:
      - targets: ['172.17.0.6:8000']  # Gradio metrics

  - job_name: 'node_exporter_gradio'
    static_configs:
      - targets: ['172.17.0.6:9100']  # Node Exporter
